"use client";

import { useState, useCallback, useEffect, useMemo } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/contexts/auth_context";
import { useI18n } from "@/contexts/i18n_context";
import type { Translate, Locale, TranslationValues } from "@/i18n/locale";
import InlineIcon from "@/components/redesign/InlineIcon";
import {
  fetch_scripts, fetch_script, update_script, delete_script,
} from "@/services/api_client";

interface ScriptItem {
  id: string;
  title: string;
  content: string;
  source_session_id: string;
  created_at: string;
  updated_at: string;
}

type Feedback = string | { zh: string; en: string; values?: TranslationValues };

const DOCUMENT_WATERMARK = "由 Marventa AI 生成 · 未付费版本保留水印";
const DOCUMENT_WATERMARK_EN = "Generated by Marventa AI · Free version watermark";
const REPORT_BRAND = "Marventa AI";
const PENDING_DOCUMENTS_STORAGE_KEY = "amp-content-generator-pending-documents-v1";

function PortfolioMark({ className }: { className?: string }) {
  return (
    <InlineIcon name="portfolio" className={className} strokeWidth={1.6} />
  );
}

interface ReportSection {
  title: string;
  paragraphs: string[];
}

interface ReportModel {
  title: string;
  date: string;
  summary: string;
  sections: ReportSection[];
}

const WATERMARK_TILES = Array.from({ length: 72 });

function read_pending_document_sessions(): string[] {
  try {
    const raw = window.localStorage.getItem(PENDING_DOCUMENTS_STORAGE_KEY);
    return raw ? JSON.parse(raw) as string[] : [];
  } catch {
    return [];
  }
}

function write_pending_document_sessions(session_ids: string[]) {
  if (session_ids.length > 0) {
    window.localStorage.setItem(PENDING_DOCUMENTS_STORAGE_KEY, JSON.stringify(session_ids));
  } else {
    window.localStorage.removeItem(PENDING_DOCUMENTS_STORAGE_KEY);
  }
}

const REPORT_HEADING_KEYWORDS = [
  "执行摘要", "项目背景", "目标", "受众", "洞察", "核心策略", "传播策略",
  "内容创意", "内容方案", "发布节奏", "风险", "优化建议", "下一步行动",
  "预算", "评估", "复盘", "结论",
];

function escape_html(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function is_report_heading(line: string): boolean {
  const clean = line.replace(/^[一二三四五六七八九十0-9]+[、.．]\s*/, "").trim();
  if (REPORT_HEADING_KEYWORDS.some((kw) => clean.includes(kw))) return true;
  return clean.length <= 18 && !/[。！？；：,.，]/.test(clean);
}

function parse_report(title: string, content: string, date: string, t: Translate, locale: Locale): ReportModel {
  const lines = (content || "")
    .replaceAll(DOCUMENT_WATERMARK, "")
    .replaceAll(DOCUMENT_WATERMARK_EN, "")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
  const first = lines[0] || title || t("综合营销策划报告", "Marketing Report");
  const reportTitle = first.length <= 80 ? first : title || t("综合营销策划报告", "Marketing Report");
  const bodyLines = first === reportTitle ? lines.slice(1) : lines;
  const sections: ReportSection[] = [];
  let current: ReportSection = { title: t("执行摘要", "Executive summary"), paragraphs: [] };

  bodyLines.forEach((line) => {
    if (is_report_heading(line)) {
      if (current.paragraphs.length > 0 || sections.length === 0) sections.push(current);
      current = { title: line.replace(/^[一二三四五六七八九十0-9]+[、.．]\s*/, ""), paragraphs: [] };
    } else {
      current.paragraphs.push(line);
    }
  });

  if (current.paragraphs.length > 0 || sections.length === 0) sections.push(current);
  const cleaned = sections
    .map((section) => ({
      title: section.title,
      paragraphs: section.paragraphs.filter((p) => p !== reportTitle),
    }))
    .filter((section) => section.paragraphs.length > 0);

  return {
    title: reportTitle,
    date: Number.isNaN(new Date(date).getTime()) ? date : new Date(date).toLocaleString(locale),
    summary: cleaned[0]?.paragraphs.slice(0, 2).join(" ") || t("这份报告整合了智能创作生成的脚本、标题、文案、话题与视觉方案，用于形成可执行的营销内容方案。", "This report brings together scripts, titles, copy, hashtags, and visual plans from Content Studio into an actionable marketing content plan."),
    sections: cleaned.length > 0 ? cleaned : [{ title: t("执行摘要", "Executive summary"), paragraphs: bodyLines.length ? bodyLines : [t("暂无正文内容。", "No report content yet.")] }],
  };
}

function watermark_layer_html(t: Translate): string {
  const tiles = WATERMARK_TILES.map(() => (
    `<span style="display:block;transform:rotate(-28deg);font-size:22px;font-weight:800;letter-spacing:.04em;color:rgba(190,18,60,.11);white-space:nowrap">${escape_html(t(DOCUMENT_WATERMARK, DOCUMENT_WATERMARK_EN))}</span>`
  )).join("");

  return `<div aria-hidden="true" style="position:absolute;inset:0;z-index:0;display:grid;grid-template-columns:repeat(2,minmax(360px,1fr));grid-auto-rows:150px;align-items:center;justify-items:center;overflow:hidden;pointer-events:none">${tiles}</div>`;
}

function report_html(report: ReportModel, t: Translate): string {
  const sections = report.sections.map((section, index) => `
    <section style="margin:0 0 26px 0;break-inside:avoid">
      <div style="display:flex;align-items:center;gap:10px;margin-bottom:10px">
        <span style="display:inline-flex;width:28px;height:28px;border-radius:50%;align-items:center;justify-content:center;background:#fff1f2;color:#be123c;font-size:12px;font-weight:700">${String(index + 1).padStart(2, "0")}</span>
        <h2 style="margin:0;color:#111827;font-size:19px;line-height:1.35">${escape_html(section.title)}</h2>
      </div>
      ${section.paragraphs.map((p) => `<p style="margin:0 0 10px 38px;color:#374151;font-size:14px;line-height:1.9;text-align:justify">${escape_html(p)}</p>`).join("")}
    </section>
  `).join("");

  return `<div style="font-family:system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:760px;margin:0 auto;color:#111827;background:white;position:relative;overflow:hidden">
    ${watermark_layer_html(t)}
    <div style="position:relative;z-index:1;padding:46px 42px 38px">
      <div style="min-height:245px;border:1px solid #e4e7ec;border-radius:12px;padding:34px;background:#f8fafc;margin-bottom:34px">
        <div style="font-size:12px;letter-spacing:.16em;text-transform:uppercase;color:#be123c;font-weight:800;margin-bottom:34px">${REPORT_BRAND}</div>
        <h1 style="font-size:32px;line-height:1.25;color:#111827;margin:0 0 18px;font-weight:800">${escape_html(report.title)}</h1>
        <p style="font-size:14px;line-height:1.9;color:#4b5563;margin:0;max-width:590px">${escape_html(report.summary)}</p>
        <div style="margin-top:28px;padding-top:18px;border-top:1px solid rgba(190,18,60,.2);display:flex;justify-content:space-between;color:#6b7280;font-size:12px">
          <span>${escape_html(t("由 {brand} 生成", "Generated by {brand}", { brand: REPORT_BRAND }))}</span>
          <span>${escape_html(report.date)}</span>
        </div>
      </div>
      ${sections}
    </div>
  </div>`;
}

export default function ScriptLibraryPage() {
  const { t, locale } = useI18n();
  const { user, loading: auth_loading } = useAuth();
  const router = useRouter();

  const [scripts, set_scripts] = useState<ScriptItem[]>([]);
  const [active, set_active] = useState<ScriptItem | null>(null);
  const [loading, set_loading] = useState(true);
  const [editing_title, set_editing_title] = useState(false);
  const [title_draft, set_title_draft] = useState("");
  const [saving, set_saving] = useState(false);
  const [toast, set_toast] = useState<Feedback | null>(null);
  const [filter_text, set_filter_text] = useState("");
  const [sort_order, set_sort_order] = useState<"newest" | "oldest">("newest");

  const show_toast = useCallback((msg: Feedback) => {
    set_toast(msg);
    setTimeout(() => set_toast(null), 3000);
  }, []);

  useEffect(() => {
    if (!auth_loading && !user) router.push("/");
  }, [user, auth_loading, router]);

  const load_scripts = useCallback(() => {
    set_loading(true);
    fetch_scripts()
      .then((res) => { if (res.success) set_scripts(res.data); })
      .catch(() => {})
      .finally(() => set_loading(false));
  }, []);

  useEffect(() => {
    if (user) load_scripts();
  }, [user, load_scripts]);

  useEffect(() => {
    if (!user) return;
    let poll_count = 0;
    let timer: ReturnType<typeof setInterval> | null = null;

    const poll_pending_documents = async () => {
      const pending = read_pending_document_sessions();
      if (pending.length === 0) {
        if (timer) clearInterval(timer);
        return;
      }

      try {
        const res = await fetch_scripts();
        if (!res.success) return;
        set_scripts(res.data);
        const remaining = pending.filter((session_id) => (
          !res.data.some((script) => script.source_session_id === session_id)
        ));
        if (remaining.length !== pending.length) {
          write_pending_document_sessions(remaining);
          show_toast({ zh: "综合文档已生成，已存入作品集", en: "Your Marketing Report is ready and has been saved to Portfolio." });
        }
        if (remaining.length === 0 && timer) clearInterval(timer);
      } catch {
        // Keep polling briefly; a transient refresh failure should not hide a completed document.
      }

      poll_count += 1;
      if (poll_count >= 40 && timer) clearInterval(timer);
    };

    if (read_pending_document_sessions().length > 0) {
      poll_pending_documents();
      timer = setInterval(poll_pending_documents, 3000);
    }

    return () => { if (timer) clearInterval(timer); };
  }, [user, show_toast]);

  const filtered_scripts = useMemo(() => {
    let result = [...scripts];
    if (filter_text.trim()) {
      const kw = filter_text.trim().toLowerCase();
      result = result.filter((s) => s.title.toLowerCase().includes(kw));
    }
    result.sort((a, b) => {
      const ta = new Date(a.updated_at).getTime();
      const tb = new Date(b.updated_at).getTime();
      return sort_order === "newest" ? tb - ta : ta - tb;
    });
    return result;
  }, [scripts, filter_text, sort_order]);

  const report = useMemo(() => (
    active ? parse_report(active.title, active.content, active.updated_at, t, locale) : null
  ), [active, t, locale]);

  const load_script = useCallback(async (id: string) => {
    try {
      const res = await fetch_script(id);
      if (res.success) {
        set_active(res.data);
        set_title_draft(res.data.title);
        set_editing_title(false);
      }
    } catch {
      show_toast({ zh: "加载失败", en: "Could not load" });
    }
  }, [show_toast]);

  const handle_save_title = useCallback(async () => {
    if (!active || !title_draft.trim()) return;
    set_saving(true);
    try {
      const res = await update_script(active.id, { title: title_draft.trim() });
      if (res.success) {
        set_active(res.data);
        set_scripts((prev) => prev.map((s) => s.id === res.data.id ? res.data : s));
        set_editing_title(false);
        show_toast({ zh: "标题已更新", en: "Title updated" });
      }
    } catch {
      show_toast({ zh: "保存失败", en: "Could not save" });
    } finally {
      set_saving(false);
    }
  }, [active, title_draft, show_toast]);

  const handle_save_content = useCallback(async () => {
    if (!active) return;
    set_saving(true);
    try {
      const res = await update_script(active.id, { content: active.content });
      if (res.success) {
        set_active(res.data);
        set_scripts((prev) => prev.map((s) => s.id === res.data.id ? res.data : s));
        show_toast({ zh: "内容已保存", en: "Content saved" });
      }
    } catch {
      show_toast({ zh: "保存失败", en: "Could not save" });
    } finally {
      set_saving(false);
    }
  }, [active, show_toast]);

  const handle_export_pdf = useCallback(async () => {
    if (!active) return;
    try {
      const html2pdf = (await import("html2pdf.js")).default;
      const report = parse_report(active.title, active.content, active.updated_at, t, locale);
      const container = document.createElement("div");
      container.innerHTML = report_html(report, t);
      document.body.appendChild(container);
      await html2pdf().set({
        margin: [12, 12, 12, 12],
        filename: `${active.title}.pdf`,
        html2canvas: { scale: 2, useCORS: true },
        jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
      }).from(container.firstElementChild as HTMLElement).save();
      document.body.removeChild(container);
    } catch {
      show_toast({ zh: "导出失败", en: "Could not export" });
    }
  }, [active, show_toast, t, locale]);

  const handle_delete = useCallback(async (id: string) => {
    if (!confirm(t("确认删除此文档？", "Delete this document?"))) return;
    try {
      await delete_script(id);
      set_scripts((prev) => prev.filter((s) => s.id !== id));
      if (active?.id === id) set_active(null);
      show_toast({ zh: "已删除", en: "Deleted" });
    } catch {
      show_toast({ zh: "删除失败", en: "Could not delete" });
    }
  }, [active, show_toast, t]);

  if (auth_loading || !user) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="w-8 h-8 border-2 border-blue-500 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="amp-redesign amp-workspace-page flex h-full min-h-0 flex-col overflow-hidden">
      <div className="amp-library-layout amp-library-shell amp-workspace-card flex min-h-0 flex-1 overflow-hidden">
      {toast && (
        <div className="fixed top-16 left-1/2 -translate-x-1/2 z-50 px-4 py-2.5 rounded-xl bg-zinc-900 dark:bg-zinc-100 text-white dark:text-zinc-900 text-sm font-medium shadow-xl">
          {typeof toast === "string" ? toast : t(toast.zh, toast.en, toast.values)}
        </div>
      )}

      {/* Left list */}
      <div className="amp-library-sidebar w-56 lg:w-72 xl:w-80 shrink-0 border-r border-zinc-200 dark:border-zinc-800 flex flex-col">
        <div className="amp-library-sidebar-header p-3 lg:p-4 border-b border-zinc-200 dark:border-zinc-800 space-y-3">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-semibold text-zinc-800 dark:text-zinc-200 font-heading">{t("作品列表", "Documents")}</h2>
            <button onClick={load_scripts} className="text-xs text-blue-700 hover:text-blue-500 cursor-pointer shrink-0 transition-colors">{t("刷新", "Refresh")}</button>
          </div>
          <div className="relative">
            <svg className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-zinc-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
            </svg>
            <input
              type="text"
              value={filter_text}
              onChange={(e) => set_filter_text(e.target.value)}
              placeholder={t("搜索关键词...", "Search keywords...")}
              className="w-full rounded-lg border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-900 pl-8 pr-3 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-400 transition-all"
            />
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => set_sort_order("newest")}
              className={`text-xs px-2.5 py-1 rounded-md transition-colors ${
                sort_order === "newest"
                  ? "bg-blue-50 text-blue-600 dark:bg-blue-950 dark:text-blue-400"
                  : "text-zinc-500 hover:text-zinc-700 dark:hover:text-zinc-300"
              }`}
            >
              {t("最新", "Newest")}
            </button>
            <button
              onClick={() => set_sort_order("oldest")}
              className={`text-xs px-2.5 py-1 rounded-md transition-colors ${
                sort_order === "oldest"
                  ? "bg-blue-50 text-blue-600 dark:bg-blue-950 dark:text-blue-400"
                  : "text-zinc-500 hover:text-zinc-700 dark:hover:text-zinc-300"
              }`}
            >
              {t("最早", "Oldest")}
            </button>
          </div>
        </div>
        <div className="flex-1 overflow-y-auto">
          {loading ? (
            <div className="p-2 space-y-2">
              {[1, 2, 3].map((i) => (
                <div key={i} className="p-3 animate-pulse">
                  <div className="h-3.5 bg-zinc-200 dark:bg-zinc-800 rounded w-3/4 mb-2" />
                  <div className="h-2.5 bg-zinc-100 dark:bg-zinc-800/50 rounded w-1/2" />
                </div>
              ))}
            </div>
          ) : scripts.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 px-4 text-center">
              <div className="w-16 h-16 rounded-xl bg-blue-50 dark:bg-blue-950 flex items-center justify-center mb-4">
                <PortfolioMark className="w-8 h-8 text-blue-500 dark:text-blue-400" />
              </div>
              <p className="text-sm font-medium text-zinc-600 dark:text-zinc-400 mb-1">{t("暂无作品", "No work yet")}</p>
              <p className="text-xs text-zinc-400 max-w-[200px]">{t("在智能创作中生成综合文档后会自动存入这里", "Marketing Reports generated in Content Studio are saved here automatically.")}</p>
            </div>
          ) : filtered_scripts.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 px-4 text-center">
              <p className="text-sm text-zinc-400">{t("无匹配记录", "No matching records")}</p>
            </div>
          ) : (
            filtered_scripts.map((s) => (
              <div
                key={s.id}
                onClick={() => load_script(s.id)}
                role="button"
                tabIndex={0}
                onKeyDown={(e) => { if (e.key === "Enter") load_script(s.id); }}
                className={`p-2 lg:p-3 border-b border-zinc-100 dark:border-zinc-900 cursor-pointer hover:bg-zinc-50 dark:hover:bg-zinc-900 transition-colors group ${
                  active?.id === s.id ? "bg-blue-50 dark:bg-blue-950 border-l-2 border-l-blue-600" : ""
                }`}
              >
                <div className="flex items-start justify-between">
                  <div className="min-w-0 flex-1">
                    <p className="text-xs lg:text-sm font-medium text-zinc-800 dark:text-zinc-200 truncate">{s.title}</p>
                    <p className="text-xs text-zinc-500 mt-0.5">{Number.isNaN(new Date(s.updated_at).getTime()) ? s.updated_at : new Date(s.updated_at).toLocaleString(locale)}</p>
                  </div>
                  <button
                    onClick={(e) => { e.stopPropagation(); handle_delete(s.id); }}
                    aria-label={t("删除文档", "Delete document")}
                    className="shrink-0 p-1 rounded-lg text-zinc-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-950 transition-colors opacity-0 group-hover:opacity-100 cursor-pointer"
                  >
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                    </svg>
                  </button>
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      {/* Right detail */}
      <div className="amp-library-content flex-1 flex flex-col overflow-y-auto bg-zinc-50/30 dark:bg-zinc-950/30">
        {active ? (
          <div className="p-6 max-w-5xl mx-auto w-full">
            {/* Title */}
            <div className="flex items-center gap-3 mb-4">
              {editing_title ? (
                <>
                  <input
                    value={title_draft}
                    onChange={(e) => set_title_draft(e.target.value)}
                    onKeyDown={(e) => { if (e.key === "Enter") handle_save_title(); if (e.key === "Escape") set_editing_title(false); }}
                    className="flex-1 px-3 py-1.5 text-lg font-semibold rounded-lg border border-blue-300 dark:border-blue-700 bg-white dark:bg-zinc-900 text-zinc-900 dark:text-zinc-100 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                    autoFocus
                  />
                  <button onClick={handle_save_title} disabled={saving} className="px-3 py-1.5 rounded-lg text-sm bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-40 cursor-pointer">
                    {t("保存", "Save")}
                  </button>
                  <button onClick={() => set_editing_title(false)} className="px-3 py-1.5 rounded-lg text-sm text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-800 cursor-pointer">
                    {t("取消", "Cancel")}
                  </button>
                </>
              ) : (
                <>
                  <h1 className="text-xl font-bold text-zinc-800 dark:text-zinc-200 font-heading">{active.title}</h1>
                  <button
                    onClick={() => { set_title_draft(active.title); set_editing_title(true); }}
                    aria-label={t("编辑标题", "Edit title")}
                    className="p-1.5 rounded-lg text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-300 hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors cursor-pointer"
                  >
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125" />
                    </svg>
                  </button>
                  <button
                    onClick={handle_export_pdf}
                    className="p-1.5 rounded-lg text-zinc-400 hover:text-blue-600 dark:hover:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-950 transition-colors cursor-pointer"
                    title={t("导出 PDF", "Export PDF")}
                  >
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
                    </svg>
                  </button>
                </>
              )}
            </div>
            <p className="text-xs text-zinc-500 mb-4">{Number.isNaN(new Date(active.updated_at).getTime()) ? active.updated_at : new Date(active.updated_at).toLocaleString(locale)}</p>

            {report && (
              <div className="mb-6 rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-zinc-100/70 dark:bg-zinc-950 p-3 lg:p-5">
                <article className="relative mx-auto max-w-4xl overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-950">
                  <div
                    aria-hidden="true"
                    className="pointer-events-none absolute inset-0 z-0 grid grid-cols-2 place-items-center overflow-hidden [grid-auto-rows:150px]"
                  >
                    {WATERMARK_TILES.map((_, index) => (
                      <span
                        key={index}
                        className="-rotate-[28deg] whitespace-nowrap text-[22px] font-black tracking-wide text-blue-600/10 dark:text-blue-200/10"
                      >
                        {t(DOCUMENT_WATERMARK, DOCUMENT_WATERMARK_EN)}
                      </span>
                    ))}
                  </div>
                  <div className="relative z-10">
                    <section className="min-h-[260px] border-b border-slate-200 bg-slate-50 px-8 py-9 dark:border-zinc-800 dark:bg-zinc-900">
                      <div className="mb-8 text-[11px] font-extrabold uppercase tracking-[0.24em] text-blue-700 dark:text-blue-300">
                        {REPORT_BRAND}
                      </div>
                      <h2 className="max-w-3xl text-3xl font-black leading-tight text-zinc-950 dark:text-zinc-50 font-heading">
                        {report.title}
                      </h2>
                      <p className="mt-5 max-w-3xl text-sm leading-7 text-zinc-600 dark:text-zinc-300">
                        {report.summary}
                      </p>
                      <div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 pt-4 text-xs text-zinc-500 dark:border-zinc-700 dark:text-zinc-400">
                        <span>{t("由 {brand} 生成", "Generated by {brand}", { brand: REPORT_BRAND })}</span>
                        <span>{report.date}</span>
                      </div>
                    </section>

                    <div className="px-8 py-8">
                      {report.sections.map((section, index) => (
                        <section key={`${section.title}-${index}`} className="mb-8 last:mb-0">
                          <div className="mb-3 flex items-center gap-3">
                            <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-50 text-xs font-bold text-blue-700 dark:bg-blue-950 dark:text-blue-300">
                              {String(index + 1).padStart(2, "0")}
                            </span>
                            <h3 className="text-lg font-bold text-zinc-900 dark:text-zinc-100">
                              {section.title}
                            </h3>
                          </div>
                          <div className="space-y-3 pl-10 text-sm leading-7 text-zinc-600 dark:text-zinc-300">
                            {section.paragraphs.map((paragraph, paragraphIndex) => (
                              <p key={`${section.title}-${paragraphIndex}`} className="text-justify">
                                {paragraph}
                              </p>
                            ))}
                          </div>
                        </section>
                      ))}
                    </div>
                  </div>
                </article>
              </div>
            )}

            {/* Content editor */}
            <div className="mb-4 rounded-xl border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-950">
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-medium text-zinc-500">{t("原文编辑", "Edit original text")}</span>
                <button
                  onClick={handle_save_content}
                  disabled={saving}
                  className="px-3 py-1 rounded-lg text-xs font-medium bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-40 transition-colors cursor-pointer"
                >
                  {saving ? t("保存中...", "Saving...") : t("保存内容", "Save content")}
                </button>
              </div>
              <textarea
                value={active.content}
                onChange={(e) => set_active({ ...active, content: e.target.value })}
                spellCheck={false}
                className="w-full h-56 px-4 py-3 text-sm rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-zinc-900 dark:text-zinc-100 resize-y focus:outline-none focus:ring-2 focus:ring-blue-500/20"
              />
            </div>
          </div>
        ) : (
          <div className="flex-1 flex items-center justify-center">
            <div className="text-center">
              <div className="w-16 h-16 mx-auto mb-4 rounded-xl bg-blue-100 dark:bg-blue-950 flex items-center justify-center">
                <PortfolioMark className="w-8 h-8 text-blue-500 dark:text-blue-400" />
              </div>
              <p className="text-sm text-zinc-500 dark:text-zinc-400">{t("选择左侧文档查看详情", "Select a document on the left to view details")}</p>
            </div>
          </div>
        )}
      </div>
    </div>
    </div>
  );
}
