import unittest

from app.database import DatabaseRow, _postgres_sql


class DatabaseBackendTests(unittest.TestCase):
    def test_database_row_supports_mapping_and_sqlite_style_indexes(self):
        row = DatabaseRow({"id": "record-1", "title": "Example"})
        self.assertEqual(row["id"], "record-1")
        self.assertEqual(row[0], "record-1")
        self.assertEqual(row[1], "Example")
        self.assertEqual(dict(row), {"id": "record-1", "title": "Example"})

    def test_postgres_sql_translates_sqlite_write_syntax(self):
        translated = _postgres_sql(
            "INSERT OR IGNORE INTO memberships (project_id, user_id) "
            "VALUES (?, ?)",
        )
        self.assertEqual(
            translated,
            "INSERT INTO memberships (project_id, user_id) "
            "VALUES (%s, %s) ON CONFLICT DO NOTHING",
        )
        self.assertEqual(_postgres_sql("BEGIN IMMEDIATE"), "BEGIN")

    def test_postgres_sql_translates_schema_and_json_expressions(self):
        self.assertEqual(
            _postgres_sql(
                "id INTEGER PRIMARY KEY AUTOINCREMENT, "
                "created_at TEXT DEFAULT (datetime('now','localtime'))",
            ),
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "created_at TEXT DEFAULT CURRENT_TIMESTAMP",
        )
        translated = _postgres_sql(
            "SELECT NULLIF(json_extract(ai_analysis, '$.product_name'), '') "
            "FROM insights WHERE json_valid(ai_analysis)",
        )
        self.assertIn("ai_analysis::jsonb ->> 'product_name'", translated)
        self.assertIn("ai_analysis IS NOT NULL", translated)

    def test_postgres_sql_preserves_existing_conflict_clause(self):
        sql = (
            "INSERT INTO memberships VALUES (?, ?) "
            "ON CONFLICT(project_id, user_id) DO UPDATE SET role = excluded.role"
        )
        translated = _postgres_sql(sql)
        self.assertEqual(translated.count("ON CONFLICT"), 1)
        self.assertIn("VALUES (%s, %s)", translated)
