from __future__ import annotations

import os
import re
import sqlite3
from collections.abc import Iterator, Mapping, Sequence
from typing import Any


class DatabaseRow(Mapping[str, Any]):
    def __init__(self, values: Mapping[str, Any]) -> None:
        self._values = dict(values)
        self._ordered = tuple(self._values.values())

    def __getitem__(self, key: str | int) -> Any:
        if isinstance(key, int):
            return self._ordered[key]
        return self._values[key]

    def __iter__(self) -> Iterator[str]:
        return iter(self._values)

    def __len__(self) -> int:
        return len(self._values)

    def keys(self):
        return self._values.keys()


class DatabaseCursor:
    def __init__(self, cursor=None, rows: list[DatabaseRow] | None = None) -> None:
        self._cursor = cursor
        self._rows = rows
        self.rowcount = (
            cursor.rowcount if cursor is not None
            else len(rows or [])
        )

    def fetchone(self) -> DatabaseRow | None:
        if self._rows is not None:
            return self._rows.pop(0) if self._rows else None
        row = self._cursor.fetchone()
        return DatabaseRow(row) if row is not None else None

    def fetchall(self) -> list[DatabaseRow]:
        if self._rows is not None:
            rows, self._rows = self._rows, []
            return rows
        return [DatabaseRow(row) for row in self._cursor.fetchall()]

    def __iter__(self) -> Iterator[DatabaseRow]:
        return iter(self.fetchall())


_INSERT_OR_IGNORE = re.compile(
    r"^\s*INSERT\s+OR\s+IGNORE\s+INTO\s+",
    re.IGNORECASE,
)
_DATETIME_DEFAULT = re.compile(
    r"DEFAULT\s*\(\s*datetime\(\s*'now'\s*,\s*'localtime'\s*\)\s*\)",
    re.IGNORECASE,
)
_JSON_VALID_CHECK = re.compile(
    r"\s+CHECK\s*\(\s*json_valid\([^)]+\)\s*\)",
    re.IGNORECASE,
)


def _postgres_sql(sql: str) -> str:
    stripped = sql.strip().rstrip(";")
    if stripped.upper() == "BEGIN IMMEDIATE":
        return "BEGIN"
    translated = _INSERT_OR_IGNORE.sub("INSERT INTO ", stripped)
    if translated != stripped and "ON CONFLICT" not in translated.upper():
        translated += " ON CONFLICT DO NOTHING"
    translated = translated.replace("?", "%s")
    translated = _DATETIME_DEFAULT.sub("DEFAULT CURRENT_TIMESTAMP", translated)
    translated = _JSON_VALID_CHECK.sub("", translated)
    translated = re.sub(
        r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(
        r"NULLIF\(json_extract\((\w+),\s*'\$\.([^']+)'\),\s*''\)",
        r"NULLIF((\1::jsonb ->> '\2'), '')",
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(
        r"\bjson_valid\((\w+)\)",
        r"(\1 IS NOT NULL AND \1 <> '')",
        translated,
        flags=re.IGNORECASE,
    )
    translated = re.sub(r"\s+COLLATE\s+NOCASE\b", "", translated, flags=re.IGNORECASE)
    translated = re.sub(r"\bLIKE\b", "ILIKE", translated, flags=re.IGNORECASE)
    translated = re.sub(
        r"\binstr\(([^,]+),\s*([^)]+)\)",
        r"strpos(\1, \2)",
        translated,
        flags=re.IGNORECASE,
    )
    return translated


class PostgresConnection:
    dialect = "postgresql"

    def __init__(self, url: str) -> None:
        import psycopg
        from psycopg.rows import dict_row

        self._psycopg = psycopg
        self._conn = psycopg.connect(url, row_factory=dict_row)
        self.total_changes = 0

    def _metadata_cursor(
        self,
        sql: str,
        params: Sequence[Any],
    ) -> DatabaseCursor | None:
        normalized = " ".join(sql.strip().split()).lower()
        pragma = re.fullmatch(r"pragma table_info\((\w+)\)", normalized)
        if pragma:
            cursor = self._conn.execute(
                """
                SELECT ordinal_position - 1 AS cid, column_name AS name,
                       data_type AS type,
                       CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END AS notnull,
                       column_default AS dflt_value,
                       CASE WHEN constraint_type = 'PRIMARY KEY' THEN 1 ELSE 0 END AS pk
                FROM information_schema.columns column_info
                LEFT JOIN (
                    SELECT key_column_usage.column_name, table_constraints.constraint_type
                    FROM information_schema.table_constraints
                    JOIN information_schema.key_column_usage
                      ON key_column_usage.constraint_name = table_constraints.constraint_name
                     AND key_column_usage.table_schema = table_constraints.table_schema
                    WHERE table_constraints.table_schema = current_schema()
                      AND table_constraints.table_name = %s
                      AND table_constraints.constraint_type = 'PRIMARY KEY'
                ) primary_key USING (column_name)
                WHERE table_schema = current_schema() AND table_name = %s
                ORDER BY ordinal_position
                """,
                (pragma.group(1), pragma.group(1)),
            )
            return DatabaseCursor(cursor)
        if "from sqlite_master" not in normalized:
            return None
        if (
            re.search(r"type\s*=\s*'table'", normalized)
            and re.search(r"name\s*=", normalized)
        ):
            table_params = tuple(params)
            if not table_params:
                literal = re.search(
                    r"name\s*=\s*'([a-z_][a-z0-9_]*)'",
                    normalized,
                )
                if not literal:
                    raise RuntimeError(
                        f"Unsupported SQLite metadata query: {sql}",
                    )
                table_params = (literal.group(1),)
            cursor = self._conn.execute(
                """
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = current_schema() AND table_name = %s
                """,
                table_params,
            )
            return DatabaseCursor(cursor)
        if normalized.startswith("select name from sqlite_master"):
            cursor = self._conn.execute(
                """
                SELECT table_name AS name
                FROM information_schema.tables
                WHERE table_schema = current_schema()
                """,
            )
            return DatabaseCursor(cursor)
        if "type = 'trigger'" in normalized:
            return DatabaseCursor(rows=[])
        raise RuntimeError(f"Unsupported SQLite metadata query: {sql}")

    def execute(
        self,
        sql: str,
        params: Sequence[Any] = (),
    ) -> DatabaseCursor:
        metadata = self._metadata_cursor(sql, params)
        if metadata is not None:
            return metadata
        translated = _postgres_sql(sql)
        if translated == "BEGIN" and self._conn.info.transaction_status != 0:
            return DatabaseCursor(rows=[])
        try:
            cursor = self._conn.execute(translated, tuple(params))
        except (
            self._psycopg.IntegrityError,
            self._psycopg.errors.RaiseException,
        ) as exc:
            raise sqlite3.IntegrityError(str(exc)) from exc
        except self._psycopg.OperationalError as exc:
            raise sqlite3.OperationalError(str(exc)) from exc
        if cursor.rowcount and cursor.rowcount > 0:
            self.total_changes += cursor.rowcount
        return DatabaseCursor(cursor)

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, _traceback) -> bool:
        if exc_type is None:
            self.commit()
        else:
            self.rollback()
        return False


def is_postgresql(conn: Any) -> bool:
    return getattr(conn, "dialect", "sqlite") == "postgresql"


def connect_database(path: str):
    from app.config import DATABASE_URL

    if DATABASE_URL:
        if not DATABASE_URL.startswith(("postgresql://", "postgres://")):
            raise ValueError("DATABASE_URL must use postgresql://")
        return PostgresConnection(DATABASE_URL)

    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    conn = sqlite3.connect(path, timeout=5.0)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA busy_timeout = 5000")
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        conn.execute("PRAGMA journal_mode = WAL")
    except sqlite3.OperationalError as exc:
        if "locked" not in str(exc).lower():
            conn.close()
            raise
    conn.execute("PRAGMA synchronous = NORMAL")
    return conn
