import type { Locale, Translate } from "@/i18n/locale";

export const DOCUMENT_WATERMARK = "由 Marventa AI 生成 · 未付费版本保留水印";
export const DOCUMENT_WATERMARK_EN = "Generated by Marventa AI · Free version watermark";
export const REPORT_BRAND = "Marventa AI";

export interface PortfolioReportSection {
  title: string;
  paragraphs: string[];
  custom?: boolean;
}

export interface PortfolioReport {
  title: string;
  date: string;
  summary: string;
  sections: PortfolioReportSection[];
}

export function hasBilingualPortfolioReport(content: string): boolean {
  try {
    const data = JSON.parse(content) as {
      schema_version?: number;
      title_zh?: string;
      title_en?: string;
      summary_zh?: string;
      summary_en?: string;
    };
    return data.schema_version === 1
      && Boolean(data.title_zh && data.title_en && data.summary_zh && data.summary_en);
  } catch {
    return false;
  }
}

const REPORT_HEADING_KEYWORDS = [
  "执行摘要", "项目背景", "目标", "受众", "洞察", "核心策略", "传播策略",
  "内容创意", "内容方案", "发布节奏", "风险", "优化建议", "下一步行动",
  "预算", "评估", "复盘", "结论",
];

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function isReportHeading(line: string): boolean {
  const clean = line.replace(/^[一二三四五六七八九十0-9]+[、.．]\s*/, "").trim();
  if (clean.length > 30 || /[。！？；.!?;]/.test(clean)) return false;
  if (REPORT_HEADING_KEYWORDS.some((keyword) => clean.includes(keyword))) return true;
  return clean.length <= 18 && !/[：:,，]/.test(clean);
}

function parseStructuredReport(
  content: string,
  date: string,
  locale: Locale,
): PortfolioReport | null {
  try {
    const data = JSON.parse(content) as {
      schema_version?: number;
      title_zh?: string;
      title_en?: string;
      summary_zh?: string;
      summary_en?: string;
      sections?: Array<{
        section_type?: string;
        title_zh?: string;
        title_en?: string;
        paragraphs_zh?: string[];
        paragraphs_en?: string[];
      }>;
    };
    if (data.schema_version !== 1 || !Array.isArray(data.sections)) return null;
    const english = locale === "en";
    const title = english ? data.title_en : data.title_zh;
    const summary = english ? data.summary_en : data.summary_zh;
    if (!title || !summary) return null;
    const sections = data.sections.map((section) => ({
      title: (english ? section.title_en : section.title_zh) || "",
      paragraphs: (english ? section.paragraphs_en : section.paragraphs_zh) || [],
      custom: section.section_type?.startsWith("custom_") || false,
    }));
    if (sections.some((section) => !section.title || section.paragraphs.length === 0)) return null;
    return {
      title,
      summary,
      sections,
      date: Number.isNaN(new Date(date).getTime()) ? date : new Date(date).toLocaleString(locale),
    };
  } catch {
    return null;
  }
}

export function parsePortfolioReport(
  title: string,
  content: string,
  date: string,
  t: Translate,
  locale: Locale,
): PortfolioReport {
  const structured = parseStructuredReport(content, date, locale);
  if (structured) return structured;

  const lines = (content || "")
    .replaceAll(DOCUMENT_WATERMARK, "")
    .replaceAll(DOCUMENT_WATERMARK_EN, "")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
  const first = lines[0] || title || t("综合营销策划报告", "Marketing report");
  const reportTitle = first.length <= 80
    ? first
    : title || t("综合营销策划报告", "Marketing report");
  const bodyLines = first === reportTitle ? lines.slice(1) : lines;
  const sections: PortfolioReportSection[] = [];
  let current: PortfolioReportSection = {
    title: t("执行摘要", "Executive summary"),
    paragraphs: [],
  };

  bodyLines.forEach((line) => {
    if (isReportHeading(line)) {
      if (current.paragraphs.length > 0 || sections.length === 0) sections.push(current);
      current = {
        title: line.replace(/^[一二三四五六七八九十0-9]+[、.．]\s*/, ""),
        paragraphs: [],
      };
    } else {
      current.paragraphs.push(line);
    }
  });

  if (current.paragraphs.length > 0 || sections.length === 0) sections.push(current);
  const cleaned = sections
    .map((section) => ({
      title: section.title,
      paragraphs: section.paragraphs.filter((paragraph) => paragraph !== reportTitle),
    }))
    .filter((section) => section.paragraphs.length > 0);
  const summary = cleaned[0]?.paragraphs.slice(0, 2).join(" ")
    || t(
      "这份作品整合了智能创作生成的内容方案，可用于后续执行与发布。",
      "This work brings together generated content into an actionable plan.",
    );
  const contentSections = cleaned[0]
    && /^(执行摘要|Executive summary)$/i.test(cleaned[0].title.trim())
    ? cleaned.slice(1)
    : cleaned;

  return {
    title: reportTitle,
    date: Number.isNaN(new Date(date).getTime()) ? date : new Date(date).toLocaleString(locale),
    summary,
    sections: cleaned.length > 0
      ? contentSections
      : [{
        title: t("作品正文", "Work content"),
        paragraphs: bodyLines.length ? bodyLines : [t("暂无正文内容。", "No content yet.")],
      }],
  };
}

export function buildPortfolioReportHtml(
  report: PortfolioReport,
  t: Translate,
  locale?: Locale,
): string {
  const watermarkTiles = Array.from({ length: 72 }, () => (
    `<span style="display:block;transform:rotate(-28deg);font-size:22px;font-weight:800;letter-spacing:.04em;color:rgba(37,99,235,.09);white-space:nowrap">${REPORT_BRAND}</span>`
  )).join("");
  const sections = report.sections.map((section, index) => `
    <section style="margin:0 0 26px;break-inside:avoid">
      <div style="display:flex;align-items:center;gap:10px;margin-bottom:10px">
        <span style="display:inline-flex;width:28px;height:28px;border-radius:50%;align-items:center;justify-content:center;background:#eff4ff;color:#175cd3;font-size:12px;font-weight:700">${String(index + 1).padStart(2, "0")}</span>
        <h2 style="margin:0;color:#111827;font-size:19px;line-height:1.35">${escapeHtml(section.title)}</h2>
      </div>
      ${section.paragraphs.map((paragraph) => `<p style="margin:0 0 10px 38px;color:#374151;font-size:14px;line-height:1.9;text-align:justify">${escapeHtml(paragraph)}</p>`).join("")}
    </section>
  `).join("");

  return `<div style="font-family:system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:760px;margin:0 auto;color:#111827;background:white;position:relative;overflow:hidden">
    <div aria-hidden="true" style="position:absolute;inset:0;z-index:0;display:grid;grid-template-columns:repeat(2,minmax(360px,1fr));grid-auto-rows:150px;align-items:center;justify-items:center;overflow:hidden;pointer-events:none">${watermarkTiles}</div>
    <div style="position:relative;z-index:1;padding:46px 42px 38px">
      <div style="min-height:245px;border:1px solid #e4e7ec;border-radius:12px;padding:34px;background:#f8fafc;margin-bottom:34px">
        <div style="font-size:12px;letter-spacing:.16em;text-transform:uppercase;color:#175cd3;font-weight:800;margin-bottom:34px">${REPORT_BRAND}</div>
        <h1 style="font-size:32px;line-height:1.25;color:#111827;margin:0 0 18px;font-weight:800">${escapeHtml(report.title)}</h1>
        <p style="font-size:14px;line-height:1.9;color:#4b5563;margin:0;max-width:590px">${escapeHtml(report.summary)}</p>
        <div style="margin-top:28px;padding-top:18px;border-top:1px solid rgba(37,99,235,.2);display:flex;justify-content:space-between;color:#6b7280;font-size:12px">
          <span>${escapeHtml(
            locale === "en"
              ? `Generated by ${REPORT_BRAND}`
              : t("由 {brand} 生成", "Generated by {brand}", { brand: REPORT_BRAND }),
          )}</span>
          <span>${escapeHtml(report.date)}</span>
        </div>
      </div>
      ${sections}
    </div>
  </div>`;
}
