import assert from "node:assert/strict";
import test from "node:test";
import {
  buildPortfolioReportHtml,
  DOCUMENT_WATERMARK,
  hasBilingualPortfolioReport,
  parsePortfolioReport,
} from "./portfolio_report.ts";

const translate = (zh: string) => zh;

test("long paragraphs containing heading keywords remain body content", () => {
  const audience = "核心受众可聚焦为年轻女性、都市生活人群、学生与职场新人，以及对可爱物件、桌面美学、情绪疗愈、轻礼物有偏好的用户。";
  const actions = "发布动作建议分为四个阶段。第一阶段，在正式发布前完成封面、标题、正文、标签和置顶评论预设，确保内容上线后能快速承接互动。";
  const report = parsePortfolioReport(
    "营销方案",
    `营销方案\n\n目标受众\n${audience}\n\n发布节奏\n${actions}`,
    "2026-09-22 00:00:00",
    translate,
    "zh-CN",
  );

  assert.deepEqual(report.sections.map((section) => section.title), ["目标受众", "发布节奏"]);
  assert.equal(report.sections[0].paragraphs[0], audience);
  assert.equal(report.sections[1].paragraphs[0], actions);
});

test("export watermark tiles only contain the Marventa AI brand", () => {
  const report = parsePortfolioReport(
    "营销方案",
    "营销方案\n\n执行摘要\n正文内容。",
    "2026-09-22 00:00:00",
    translate,
    "zh-CN",
  );
  const html = buildPortfolioReportHtml(report, translate);

  assert.equal(html.includes(DOCUMENT_WATERMARK), false);
  assert.equal((html.match(/>Marventa AI<\/span>/g) || []).length, 72);
});

test("execution summary is not repeated as a content section", () => {
  const summary = "本次策划围绕新品传播展开，形成完整的内容执行方案。";
  const report = parsePortfolioReport(
    "营销方案",
    `营销方案\n\n执行摘要\n${summary}\n\n项目背景与目标\n建立品牌认知。`,
    "2026-09-22 00:00:00",
    translate,
    "zh-CN",
  );

  assert.equal(report.summary, summary);
  assert.deepEqual(report.sections.map((section) => section.title), ["项目背景与目标"]);
});

test("structured reports select the version matching the interface language", () => {
  const content = JSON.stringify({
    schema_version: 1,
    title_zh: "中文报告",
    title_en: "English Report",
    summary_zh: "中文摘要",
    summary_en: "English summary",
    sections: [{
      title_zh: "项目背景与目标",
      title_en: "Project Background and Goals",
      paragraphs_zh: ["中文正文"],
      paragraphs_en: ["English content"],
    }],
  });

  const chinese = parsePortfolioReport(
    "fallback", content, "2026-09-22 00:00:00", translate, "zh-CN",
  );
  const english = parsePortfolioReport(
    "fallback", content, "2026-09-22 00:00:00", translate, "en",
  );

  assert.equal(chinese.title, "中文报告");
  assert.equal(chinese.sections[0].paragraphs[0], "中文正文");
  assert.equal(english.title, "English Report");
  assert.equal(english.sections[0].paragraphs[0], "English content");
  assert.equal(hasBilingualPortfolioReport(content), true);
  assert.match(buildPortfolioReportHtml(english, translate, "en"), /Generated by Marventa AI/);
});
